language: java
install: true
jdk: oraclejdk8
env:
  matrix:
  - TERM=dumb
before_script:
  - ./gradlew --version
script: ./gradlew -Pskip-long-running build
after_success:
  - ./gradlew -Pskip-long-running jacocoTestReport coveralls